#!/usr/bin/env python3
"""Extract L3 matrices from Lynx parameter files and generate a C++ header.

Reads lynx-design/parameter/OurNewVOLEitH*.txt, extracts Mat 3 (L3) for each
security level, and outputs lynx_l3_consts.hpp with precomputed constant arrays.

Usage:
    python3 tools/gen_lynx_l3_matrices.py > lynx_l3_consts.hpp
"""

import os
import sys
from pathlib import Path


PARAM_DIR = Path(__file__).parent.parent / "lynx-design" / "parameter"

PARAM_FILES = {
    128: "OurNewVOLEitH128.txt",
    192: "OurNewVOLEitH192.txt",
    256: "OurNewVOLEitH256.txt",
    384: "OurNewVOLEitH384.txt",
    512: "OurNewVOLEitH512.txt",
}


def parse_matrix(filepath: Path, mat_index: int, n: int) -> list[list[int]]:
    """Parse matrix mat_index from a parameter file. Returns list of N rows, each a list of N bits."""
    with open(filepath) as f:
        lines = f.readlines()

    # Find the start of the target matrix
    mat_count = -1
    start_line = None
    for i, line in enumerate(lines):
        if line.strip().startswith("Mat "):
            mat_count += 1
            if mat_count == mat_index:
                start_line = i + 1
                break

    if start_line is None:
        raise ValueError(f"Matrix {mat_index} not found in {filepath}")

    rows = []
    for i in range(start_line, start_line + n):
        line = lines[i].strip()
        # Remove leading [[ or [ and trailing ]] or ]
        line = line.lstrip("[").rstrip("]")
        bits = [int(b) for b in line.split()]
        assert len(bits) == n, f"Row {i - start_line} has {len(bits)} bits, expected {n}"
        rows.append(bits)

    assert len(rows) == n
    return rows


def pack_row(bits: list[int]) -> list[int]:
    """Pack a row of bits into uint64_t words. Bit j goes into word j//64, position j%64."""
    n = len(bits)
    w = (n + 63) // 64
    words = [0] * w
    for j, b in enumerate(bits):
        if b:
            words[j // 64] |= 1 << (j % 64)
    return words


def format_uint64(v: int) -> str:
    return f"UINT64_C(0x{v:016x})"


def self_test():
    """Verify matrices are square and have expected dimensions."""
    for n, filename in PARAM_FILES.items():
        filepath = PARAM_DIR / filename
        if not filepath.exists():
            print(f"WARNING: {filepath} not found, skipping", file=sys.stderr)
            continue
        mat = parse_matrix(filepath, 3, n)
        assert len(mat) == n, f"L3 for {n} has {len(mat)} rows"
        for i, row in enumerate(mat):
            assert len(row) == n, f"L3 for {n}, row {i} has {len(row)} bits"
        print(f"L3 for GF(2^{n}): {n}x{n} matrix OK", file=sys.stderr)
    print("All self-tests passed.", file=sys.stderr)


def generate_header():
    lines = []
    lines.append("// AUTO-GENERATED by tools/gen_lynx_l3_matrices.py — DO NOT EDIT")
    lines.append("#ifndef LYNX_L3_CONSTS_HPP")
    lines.append("#define LYNX_L3_CONSTS_HPP")
    lines.append("")
    lines.append("#include <array>")
    lines.append("#include <cstdint>")
    lines.append("#include <cstddef>")
    lines.append('#include "parameters.hpp"')
    lines.append("")
    lines.append("namespace faest {")
    lines.append("namespace lynx {")
    lines.append("")

    secpar_names = {128: "s128", 192: "s192", 256: "s256", 384: "s384", 512: "s512"}

    for n, filename in sorted(PARAM_FILES.items()):
        filepath = PARAM_DIR / filename
        mat = parse_matrix(filepath, 3, n)
        w = (n + 63) // 64
        name = f"lynx_l3_{n}"

        lines.append(f"inline const std::array<std::array<uint64_t, {w}>, {n}> {name} = {{{{")
        for i, row in enumerate(mat):
            words = pack_row(row)
            word_str = ", ".join(format_uint64(v) for v in words)
            comma = "," if i < n - 1 else ""
            lines.append(f"    {{{{{word_str}}}}}{comma}")
        lines.append("}};")
        lines.append("")

    # Dispatch: use a struct with static method to avoid auto return type issues
    lines.append("template <secpar S>")
    lines.append("struct lynx_l3_dispatch;")
    lines.append("")

    for n in sorted(PARAM_FILES.keys()):
        w = (n + 63) // 64
        sname = secpar_names[n]
        lines.append(f"template <> struct lynx_l3_dispatch<secpar::{sname}> {{")
        lines.append(f"    static const std::array<std::array<uint64_t, {w}>, {n}>& get() {{ return lynx_l3_{n}; }}")
        lines.append("};")
        lines.append("")

    lines.append("template <secpar S>")
    lines.append("inline const auto& lynx_l3_matrix() { return lynx_l3_dispatch<S>::get(); }")
    lines.append("")

    lines.append("} // namespace lynx")
    lines.append("} // namespace faest")
    lines.append("")
    lines.append("#endif // LYNX_L3_CONSTS_HPP")
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    self_test()
    print(generate_header())
