#!/usr/bin/env python3
"""
Generate lynx_owf_consts.h from the LYNX design parameter files.

Usage: python3 tools/gen_lynx_consts.py
Run from the repository root. Output: lynx_owf_consts.h
"""

import re
import sys
import os

PARAM_DIR = os.path.join(os.path.dirname(__file__), '..', 'lynx-design', 'parameter')
OUT_FILE  = os.path.join(os.path.dirname(__file__), '..', 'lynx_owf_consts.h')

# Security parameters we need
SIZES = [128, 192, 256, 384, 512]

# Map n -> matrix filename
MATRIX_FILES = {
    128: 'OurNewVOLEitH128.txt',
    192: 'OurNewVOLEitH192.txt',
    256: 'OurNewVOLEitH256.txt',
    384: 'OurNewVOLEitH384.txt',
    512: 'OurNewVOLEitH512.txt',
}

# --------------------------------------------------------------------------
# Parse constant.txt: returns dict {n: (c0_bytes, c1_bytes)}
# --------------------------------------------------------------------------
def parse_constants(path):
    result = {}
    with open(path, encoding='utf-8') as f:
        text = f.read()

    # Find blocks like "128：\nc0:...\nc1:..."
    for n in SIZES:
        # Match "128" or "128：" as header then c0 and c1
        pat = rf'{n}[：:]?\s*\nc0:([0-9a-f_]+)\nc1:([0-9a-f_]+)'
        m = re.search(pat, text)
        if not m:
            # Try without colon variant
            pat = rf'{n}\s*\nc0:([0-9a-f_]+)\nc1:([0-9a-f_]+)'
            m = re.search(pat, text)
        if not m:
            print(f'WARNING: constants for n={n} not found', file=sys.stderr)
            continue
        c0_hex = m.group(1).replace('_', '')
        c1_hex = m.group(2).replace('_', '')
        c0 = bytes.fromhex(c0_hex)
        c1 = bytes.fromhex(c1_hex)
        assert len(c0) == n // 8, f'n={n}: c0 length mismatch {len(c0)} vs {n//8}'
        assert len(c1) == n // 8, f'n={n}: c1 length mismatch {len(c1)} vs {n//8}'
        result[n] = (c0, c1)
    return result

# --------------------------------------------------------------------------
# Parse a matrix file: returns list of 4 matrices (L0..L3).
# Each matrix is a list of n rows; each row is a list of n ints (0 or 1).
# --------------------------------------------------------------------------
def parse_matrices(path, n):
    matrices = []
    current = None

    with open(path, encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')
            if line.startswith('Mat '):
                if current is not None:
                    matrices.append(current)
                current = []
                continue
            # Strip leading [[ or [ and trailing ] or ]]
            stripped = line.strip().lstrip('[').rstrip(']')
            if not stripped:
                continue
            bits = [int(b) for b in stripped.split()]
            if len(bits) == n:
                current.append(bits)

    if current is not None:
        matrices.append(current)

    assert len(matrices) == 4, f'{path}: expected 4 matrices, got {len(matrices)}'
    for i, m in enumerate(matrices):
        assert len(m) == n, f'{path}: Mat {i} has {len(m)} rows, expected {n}'
        for j, row in enumerate(m):
            assert len(row) == n, f'{path}: Mat {i} row {j} has {len(row)} cols, expected {n}'
    return matrices  # [L0, L1, L2, L3]

# --------------------------------------------------------------------------
# Pack a matrix row (list of n bits) into uint64_t words, LSB-first.
# Bit j of the row -> bit (j%64) of word (j//64).
# --------------------------------------------------------------------------
def pack_row(bits):
    n = len(bits)
    nwords = (n + 63) // 64
    words = [0] * nwords
    for j, b in enumerate(bits):
        words[j // 64] |= b << (j % 64)
    return words

# --------------------------------------------------------------------------
# Format helpers
# --------------------------------------------------------------------------
def fmt_bytes(data, cols=8):
    lines = []
    for i in range(0, len(data), cols):
        chunk = data[i:i+cols]
        lines.append('    ' + ', '.join(f'0x{b:02x}' for b in chunk))
    return ',\n'.join(lines)

def fmt_u64(words):
    return ', '.join(f'UINT64_C(0x{w:016x})' for w in words)

# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------
def main():
    const_path = os.path.join(PARAM_DIR, 'constant.txt')
    constants  = parse_constants(const_path)

    lines = []
    lines.append('/*')
    lines.append(' * lynx_owf_consts.h - LYNX OWF constants (auto-generated by tools/gen_lynx_consts.py)')
    lines.append(' * DO NOT EDIT MANUALLY.')
    lines.append(' */')
    lines.append('#ifndef LYNX_OWF_CONSTS_H')
    lines.append('#define LYNX_OWF_CONSTS_H')
    lines.append('')
    lines.append('#include <stdint.h>')
    lines.append('')

    for n in SIZES:
        if n not in constants:
            continue
        c0, c1 = constants[n]
        nwords  = n // 64

        mat_path  = os.path.join(PARAM_DIR, MATRIX_FILES[n])
        matrices  = parse_matrices(mat_path, n)
        mat_names = ['L0', 'L1', 'L2', 'L3']

        lines.append(f'/* ---- n = {n} ---- */')
        lines.append('')

        # c0
        lines.append(f'static const uint8_t LYNX_C0_{n}[{n // 8}] = {{')
        lines.append(fmt_bytes(c0))
        lines.append('};')
        lines.append('')

        # c1
        lines.append(f'static const uint8_t LYNX_C1_{n}[{n // 8}] = {{')
        lines.append(fmt_bytes(c1))
        lines.append('};')
        lines.append('')

        # Matrices L0..L3
        for mi, (mat, name) in enumerate(zip(matrices, mat_names)):
            lines.append(f'/* {name} for n={n}: {n}x{n} matrix over GF(2), row-major, LSB-first */')
            lines.append(f'static const uint64_t LYNX_{name}_{n}[{n}][{nwords}] = {{')
            row_strs = []
            for row in mat:
                words = pack_row(row)
                row_strs.append('    { ' + fmt_u64(words) + ' }')
            lines.append(',\n'.join(row_strs))
            lines.append('};')
            lines.append('')

    lines.append('#endif /* LYNX_OWF_CONSTS_H */')

    out = '\n'.join(lines) + '\n'
    with open(OUT_FILE, 'w') as f:
        f.write(out)
    print(f'Written {OUT_FILE}  ({len(out):,} bytes)')

if __name__ == '__main__':
    main()
