/*
 * Generate precomputed Frobenius matrices for all Lynx parameter sizes.
 * Build: cc -O2 -I.. -DHAVE_CONFIG_H -Ibuild -o gen_frob gen_frob_matrices.c ../fields.c ../randomness.c
 */
#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "fields.h"

static void ptr_set_bit(uint8_t* buf, unsigned int bit, int val) {
  if (val)
    buf[bit / 8] |= (uint8_t)(1u << (bit % 8));
  else
    buf[bit / 8] &= (uint8_t)~(1u << (bit % 8));
}

/* ---- 192 ---- */
static void print_192(const char* name, unsigned int power) {
  uint64_t M[192][3];
  memset(M, 0, sizeof(M));
  for (unsigned int col = 0; col < 192; ++col) {
    uint8_t b[24] = {0};
    ptr_set_bit(b, col, 1);
    bf192_t basis = bf192_load(b);
    for (unsigned int i = 0; i < power; ++i)
      basis = bf192_mul(basis, basis);
    uint8_t img[24];
    bf192_store(img, basis);
    for (unsigned int row = 0; row < 192; ++row)
      if ((img[row / 8] >> (row % 8)) & 1)
        M[row][col / 64] |= (UINT64_C(1) << (col % 64));
  }
  printf("static const uint64_t %s[192][3] = {\n", name);
  for (unsigned int r = 0; r < 192; ++r) {
    printf("    {UINT64_C(0x%016llx), UINT64_C(0x%016llx), UINT64_C(0x%016llx)}",
           (unsigned long long)M[r][0], (unsigned long long)M[r][1],
           (unsigned long long)M[r][2]);
    printf("%s\n", r < 191 ? "," : "");
  }
  printf("};\n\n");
}

/* ---- 256 ---- */
static void print_256(const char* name, unsigned int power) {
  uint64_t M[256][4];
  memset(M, 0, sizeof(M));
  for (unsigned int col = 0; col < 256; ++col) {
    uint8_t b[32] = {0};
    ptr_set_bit(b, col, 1);
    bf256_t basis = bf256_load(b);
    for (unsigned int i = 0; i < power; ++i)
      basis = bf256_mul(basis, basis);
    uint8_t img[32];
    bf256_store(img, basis);
    for (unsigned int row = 0; row < 256; ++row)
      if ((img[row / 8] >> (row % 8)) & 1)
        M[row][col / 64] |= (UINT64_C(1) << (col % 64));
  }
  printf("static const uint64_t %s[256][4] = {\n", name);
  for (unsigned int r = 0; r < 256; ++r) {
    printf("    {UINT64_C(0x%016llx), UINT64_C(0x%016llx), "
           "UINT64_C(0x%016llx), UINT64_C(0x%016llx)}",
           (unsigned long long)M[r][0], (unsigned long long)M[r][1],
           (unsigned long long)M[r][2], (unsigned long long)M[r][3]);
    printf("%s\n", r < 255 ? "," : "");
  }
  printf("};\n\n");
}

/* ---- 384 ---- */
static void print_384(const char* name, unsigned int power) {
  uint64_t M[384][6];
  memset(M, 0, sizeof(M));
  for (unsigned int col = 0; col < 384; ++col) {
    uint8_t b[48] = {0};
    ptr_set_bit(b, col, 1);
    bf384_t basis = bf384_load(b);
    for (unsigned int i = 0; i < power; ++i)
      basis = bf384_mul(basis, basis);
    uint8_t img[48];
    bf384_store(img, basis);
    for (unsigned int row = 0; row < 384; ++row)
      if ((img[row / 8] >> (row % 8)) & 1)
        M[row][col / 64] |= (UINT64_C(1) << (col % 64));
  }
  printf("static const uint64_t %s[384][6] = {\n", name);
  for (unsigned int r = 0; r < 384; ++r) {
    printf("    {UINT64_C(0x%016llx), UINT64_C(0x%016llx), UINT64_C(0x%016llx), "
           "UINT64_C(0x%016llx), UINT64_C(0x%016llx), UINT64_C(0x%016llx)}",
           (unsigned long long)M[r][0], (unsigned long long)M[r][1],
           (unsigned long long)M[r][2], (unsigned long long)M[r][3],
           (unsigned long long)M[r][4], (unsigned long long)M[r][5]);
    printf("%s\n", r < 383 ? "," : "");
  }
  printf("};\n\n");
}

/* ---- 512 ---- */
static void print_512(const char* name, unsigned int power) {
  uint64_t M[512][8];
  memset(M, 0, sizeof(M));
  for (unsigned int col = 0; col < 512; ++col) {
    uint8_t b[64] = {0};
    ptr_set_bit(b, col, 1);
    bf512_t basis = bf512_load(b);
    for (unsigned int i = 0; i < power; ++i)
      basis = bf512_mul(basis, basis);
    uint8_t img[64];
    bf512_store(img, basis);
    for (unsigned int row = 0; row < 512; ++row)
      if ((img[row / 8] >> (row % 8)) & 1)
        M[row][col / 64] |= (UINT64_C(1) << (col % 64));
  }
  printf("static const uint64_t %s[512][8] = {\n", name);
  for (unsigned int r = 0; r < 512; ++r) {
    printf("    {UINT64_C(0x%016llx), UINT64_C(0x%016llx), UINT64_C(0x%016llx), UINT64_C(0x%016llx), "
           "UINT64_C(0x%016llx), UINT64_C(0x%016llx), UINT64_C(0x%016llx), UINT64_C(0x%016llx)}",
           (unsigned long long)M[r][0], (unsigned long long)M[r][1],
           (unsigned long long)M[r][2], (unsigned long long)M[r][3],
           (unsigned long long)M[r][4], (unsigned long long)M[r][5],
           (unsigned long long)M[r][6], (unsigned long long)M[r][7]);
    printf("%s\n", r < 511 ? "," : "");
  }
  printf("};\n\n");
}

int main(void) {
  printf("/*\n * Precomputed Frobenius matrices for Lynx proof constraints.\n");
  printf(" * Generated by tools/gen_frob_matrices.c — do not edit.\n */\n\n");
  printf("#ifndef LYNX_FROB_CONSTS_H\n#define LYNX_FROB_CONSTS_H\n\n");
  printf("#include <stdint.h>\n\n");

  /* 192: powers 59, 13 */
  print_192("frob192_59", 59);
  print_192("frob192_13", 13);

  /* 256: powers 53, 1, 5 */
  print_256("frob256_53", 53);
  print_256("frob256_1", 1);
  print_256("frob256_5", 5);

  /* 384: powers 60, 30, 13 */
  print_384("frob384_60", 60);
  print_384("frob384_30", 30);
  print_384("frob384_13", 13);

  /* 512: powers 180, 90, 6, 12 */
  print_512("frob512_180", 180);
  print_512("frob512_90", 90);
  print_512("frob512_6", 6);
  print_512("frob512_12", 12);

  printf("#endif /* LYNX_FROB_CONSTS_H */\n");
  return 0;
}
